const aartis = [
  {
    titleMarathi: "सुखकर्ता दुःखहर्ता",
    titleEnglish: "Sukhkarta Dukhharta – Ganpati Aarti",
    marathi: [
      "सुखकर्ता दुःखहर्ता वार्ता विघ्नाची ।",
      "नुरवी पुरवी प्रेम कृपा जयाची ॥ धृ ॥",
      "सर्वांगी सुंदर उटी शेंदुराची ।",
      "कंठी झळके माळ मुक्ताफळांची ॥ जया ॥ १ ॥",
      "जय देव जय देव जय मंगलमूर्ती ।",
      "दर्शनमात्रे मनःकामना पूर्ती ।",
      "रत्नखचित फरा तुज गौरीकुमरा ।",
      "चंदनाची उटी कुंकुमकेशरा ।",
      "हिरेजडित मुकुट शोभतो बरा ।",
      "रुणझुणती नूपुरे चरणी घागरिया ॥ जया ॥ २ ॥",
      "लंबोदर पीतांबर फणिवरबंधना ।",
      "सरळ सोंड वक्रतुंड त्रिनयना ।",
      "दास रामाचा वाट पाहे सदना ।",
      "संकटी पावावे निर्वाणी रक्षावे सुरवर वंदना ।",
      "जय देव जय देव जय मंगलमूर्ती ।",
      "दर्शनमात्रे मनःकामना पूर्ती ॥ जया ॥ ३ ॥",
    ],
    englishLyrics: [
      "Sukhkarta dukhharta varta vighnachi.",
      "Nurvi purvi prem krupa jayachi. (Refrain)",
      "Sarvangi sundar uti shendurachi.",
      "Kanthi zhalake maal muktaphalaanchi. (Jaya 1)",
      "Jai dev jai dev jai mangalmurti.",
      "Darshanmatre manah kaamana purti.",
      "Ratnakhachit phara tuj gaurikumara!",
      "Chandnachi uti kunkumakeshara.",
      "Hirejadit mukut shobhato bara.",
      "Runjhunti nupure charni ghagariya. (Jaya 2)",
      "Lambodar pitambar phanivar bandhana.",
      "Saral sond vakra tund trinayana.",
      "Daas Ramacha vat pahe sadana.",
      "Sankati paavaave nirvaani rakshaave survar vandana.",
      "Jai dev jai dev jai mangalmurti.",
      "Darshanmatre manah kaamana purti. (Jaya 3)",
    ],
    english: [
      "Sukhkarta Dukhharta – the one who removes sorrow and grants happiness, remove all obstacles.",
      "Fill our lives with love, grace and blessings.",
      "Your entire form is beautiful and adorned with vermilion.",
      "A pearl necklace shines around your neck.",
      "Victory to you, O auspicious and divine form.",
      "Just seeing you fulfills the wishes of the heart.",
      "O son of Goddess Gauri, adorned with precious jewels.",
      "Your forehead is decorated with sandalwood and saffron.",
      "Your diamond-studded crown shines beautifully.",
      "Your anklets ring melodiously as you walk.",
      "O large-bellied Lord wearing yellow garments.",
      "With your straight trunk, curved form and three eyes.",
      "Your devotee waits for you with devotion.",
      "Protect us during difficult times and bless us.",
      "Victory to you, O auspicious and divine form.",
      "Your divine presence fulfills the wishes of the heart.",
    ],
  },
  {
    titleMarathi: "श्री शंकराची आरती",
    titleEnglish: "Shri Shankarachi Aarti",
    marathi: [
      "लवथवती विक्राळा ब्रह्मांडी माळा ।",
      "विषें कंठ काळा त्रिनेत्री ज्वाळा ॥",
      "लावण्यसुंदर मस्तकी बाळा ।",
      "तेथुनियां जळ निर्मळ वाहे झुळझुळा ।",
      "जय देव जय देव श्रीशंकरा ।",
      "आरती ओवाळूं तुज कर्पूरगौरा ॥ १ ॥",
      "कर्पूरगौरा भोळा नयनी विशाळा ।",
      "अर्धांगी पार्वती सुमनांच्या माळा ।",
      "विभूतीचे उधळण शितिकंठ नीळा ।",
      "ऐसा शंकर शोभे उमावेल्हाळा जय ॥ २ ॥",
      "देवी दैत्य सागरमंथन पै केले ।",
      "त्यामाजी अवचित हलाहल उठिले ।",
      "तें त्वां असुरपणे प्राशन केले ।",
      "नीलकंठ नाम प्रसिद्ध झाले ॥ जया ॥ ३ ॥",
      "व्याघ्रांबर फणिवरधर सुंदर मदनारी ।",
      "पंचवदन मनमोहन मुनिजनसुखकारी ।",
      "शतकोटींचे बीज वाचे उच्चारी ।",
      "रघुकुळटिळक रामदासा अंतरी ॥ जय ॥ ४ ॥",
    ],
    englishLyrics: [
      "Lavathavati vikraala brahmandi maala.",
      "Vishe kanth kaala trinetri jwala.",
      "Lavanya sundar mastki baala.",
      "Tethuniya jal nirmal vahe zhulzhula.",
      "Jai dev jai dev Shri Shankara.",
      "Aarti ovalu tuj karpurgaura. (1)",
      "Karpurgaura bhola nayani vishaala.",
      "Ardhangi Parvati sumnanchya maala.",
      "Vibhutiche udhalan shitikanth neela.",
      "Aisa Shankar shobhe Umavelhala. (2)",
      "Devi daitya sagar-manthan pai kele.",
      "Tyamaji avchit halahal uthile.",
      "Te twa asur-pane prashan kele.",
      "Neelkanth naam prasiddh zale. (3)",
      "Vyaghrambar phanivardhar sundar madanari.",
      "Panchvadan manmohan munijan sukhkari.",
      "Shatkotinche beej vache uchhari.",
      "Raghukulatilak Ramdasa antari. (4)",
    ],
    english: [
      "O Lord Shiva, mighty and magnificent throughout the universe.",
      "Your throat is darkened by poison and your three eyes shine like flames.",
      "Your form is beautiful and divine.",
      "Pure water flows gently from your sacred locks.",
      "Victory to Lord Shankara.",
      "We offer this camphor Aarti to you, O radiant Lord.",
      "You are pure, simple and compassionate, with large beautiful eyes.",
      "Goddess Parvati is your divine consort.",
      "Your blue throat and sacred ash make you majestic.",
      "Such is the beautiful form of Lord Shankara.",
      "During the churning of the ocean, deadly poison emerged.",
      "You drank the poison to protect the world.",
      "Because of this your throat became blue.",
      "You became famous as Neelkanth.",
      "You wear tiger skin and carry the serpent.",
      "Your five-faced form is beautiful and brings happiness to sages.",
      "Your divine name is praised with devotion.",
    ],
  },
  {
    titleMarathi: "दुर्गादेवीची आरती",
    titleEnglish: "Durgadevichi Aarti",
    marathi: [
      "दुर्गे दुर्घट भारी तुजविण संसारी ।",
      "अनाथनाथे अंबे करुणा विस्तारी ॥",
      "वारी वारी जन्ममरणाते वारी ।",
      "हारी पडलों आता संकट निवारी ॥",
      "जय देवी जय देवी महिषासुरमथिनी ।",
      "सुरवरईश्वरवरदे तारक संजीवनी ॥ जय ॥ १ ॥",
      "त्रिभुवनभुवनी पाहतां तुज ऐसी नाही ।",
      "चारी श्रमले परंतु न बोलवे काही ॥",
      "साही विवाद करितां पडले प्रवाही ।",
      "ते तूं भक्तालागीं पावसि लवलाही ॥ जय ॥ २ ॥",
      "प्रसन्नवदने प्रसन्न होसी निजदासा ।",
      "क्लेशापासुनी सोडी तोडी भवपाशा ।",
      "अंबे तुजवाचून कोण पुरवील आशा ।",
      "नरहरी तल्लीन झाला पदपंकजलेशा ॥ जय ॥ ३ ॥",
    ],
    englishLyrics: [
      "Durge durghat bhari tujavin sansari.",
      "Anathnathe Ambe karuna vistari.",
      "Vari vari janm-maranate vari.",
      "Hari padlo aata sankat nivari.",
      "Jai devi jai devi Mahishasur mathini.",
      "Suravar-Ishvar-varade tarak sanjivani. (1)",
      "Tribhuvanbhuvani pahata tuj aisi nahi.",
      "Chaari shramale parantu na bolave kahi.",
      "Saahi vivaad karita padle pravahi.",
      "Te tu bhaktalagi pavsi lavlahi. (2)",
      "Prasannvadane prasann hosi nijdasa.",
      "Kleshapasuni sodi todi bhavpasha.",
      "Ambe tujavachun kon purvil aasha.",
      "Narahari tallin zhala padpankaj-lesha. (3)",
    ],
    english: [
      "O Goddess Durga, the world is difficult without you.",
      "O Mother of the helpless, spread your compassion upon us.",
      "Protect us from the endless cycle of birth and death.",
      "We have fallen into difficulties; please remove our troubles.",
      "Victory to Goddess Durga, destroyer of Mahishasura.",
      "You grant blessings and protect the divine and devoted.",
      "There is none like you in all the three worlds.",
      "Even after trying to describe you, words fall short.",
      "Those who debate your greatness are left without words.",
      "You quickly come to the aid of your devotees.",
      "With your pleasant face, you bless your devoted servants.",
      "Free us from suffering and from the bonds of worldly life.",
      "O Mother, who else can fulfill our deepest hopes?",
      "Your devotee becomes completely absorbed at your lotus feet.",
    ],
  },
  {
    titleMarathi: "विठोबाची आरती",
    titleEnglish: "Vitthobachi Aarti",
    marathi: [
      "युगे अठ्ठावीस विटेवरी उभा ।",
      "वामांगी रखुमाई दिसे दिव्य शोभा ।",
      "पुंडलिकाचे भेटी परब्रह्म आले गा ।",
      "चरणी वाहे भीमा उद्धरी जगा ।",
      "जय देव जय देव जय पांडुरंगा ।",
      "रखुमाईवल्लभा राईच्या वल्लभा पावे जिवलगा ॥ १ ॥",
      "तुळशीमाळा गळां कर ठेवुनी कटी ।",
      "कांसे पीतांबर कस्तुरी लल्लाटीं ।",
      "देव सुरवर नित्य येती भेटी ।",
      "गरुड हनुमंत पुढे उभे राहती ॥ २ ॥",
      "धन्य वेणुनाद अनुपाळा गळा ।",
      "सुवर्णाची कमळे चरणाला गळा ।",
      "राई रखुमाई राणीया सकळा ।",
      "ओवाळिती राजा विठोबा सावळा ॥ ३ ॥",
      "ओवाळू आरत्या कुर्वंड्या येती ।",
      "चंद्रभागेमाजी सोडुनिया देती ।",
      "दिंड्या पताका वैष्णव नाचती ।",
      "पंढरीचा महिमा वर्णावा किती ॥ ४ ॥",
      "आषाढी कार्तिकी भक्तजन येती ।",
      "चंद्रभागेमाजी स्नान जे करती ।",
      "दर्शन होताचि तया होय मुक्ति ।",
      "केशवासी नामदेव भावे ओवाळिती ॥ ५ ॥",
    ],
    englishLyrics: [
      "Yuge atthavis vitevari ubha.",
      "Vamangi Rakhumai dise divya shobha.",
      "Pundalikache bheti parbrahma aale ga.",
      "Charani vahe Bhima uddhari jaga.",
      "Jai dev jai dev jai Panduranga.",
      "Rakhumaivallabha Raicheya vallabha pave jivalga. (1)",
      "Tulsimala gala kar thevuni kati.",
      "Kanse pitambar kasturi lallati.",
      "Dev suravar nitya yeti bheti.",
      "Garud Hanumant pudhe ubhe rahati. (2)",
      "Dhanya venunad anupala gala.",
      "Suvarnachi kamale charnala gala.",
      "Rai Rakhumai raniya sakala.",
      "Ovaliti raja Vitthoba savala. (3)",
      "Ovalu aartya kurvandya yeti.",
      "Chandrabhagemaji soduniya deti.",
      "Dindya pataka Vaishnav nachati.",
      "Pandharicha mahima varnava kiti. (4)",
      "Ashadhi Kartiki bhakta-jan yeti.",
      "Chandrabhagemaji snan je karati.",
      "Darshan hotach taya hoy mukti.",
      "Keshvasi Namdev bhave ovaliti. (5)",
    ],
    english: [
      "For twenty-eight ages, you stand upon the sacred brick.",
      "Rukmini stands beside you in divine beauty.",
      "The Supreme Being came to meet devotee Pundalik.",
      "The Bhima River flows at your feet and blesses the world.",
      "Victory to Panduranga, the beloved Lord.",
      "Beloved of Rukmini and the devotee's cherished Lord.",
      "You wear a Tulsi garland and rest your hands upon your waist.",
      "You wear yellow garments with sandalwood and musk adorning you.",
      "Gods and divine beings come to see you every day.",
      "Garuda and Hanuman stand before you.",
      "The beautiful sound of the flute fills the surroundings.",
      "Golden lotuses adorn your sacred feet.",
      "Rukmini and the divine queens worship you.",
      "They perform Aarti to the beautiful dark form of Vitthoba.",
      "Devotees gather with Aarti and offerings.",
      "Devotees bathe in the Chandrabhaga River.",
      "Processions and Vaishnav devotees dance with flags.",
      "The greatness of Pandharpur cannot be fully described.",
      "Devotees arrive during Ashadhi and Kartiki.",
      "Those who bathe in the Chandrabhaga receive blessings.",
      "A vision of the Lord brings liberation.",
      "Devotees lovingly offer Aarti to Lord Keshava.",
    ],
  },
  {
    titleMarathi: "येई हो विठ्ठले",
    titleEnglish: "Yeyi ho vitthale",
    marathi: [
      "येई हो विठ्ठले माझे माउली ये ।",
      "निढळावरी कर ठेवूनि वाट मी पाहे ॥ धृ ॥",
      "आलिया गेलिया हाती धाडी निरोप ।",
      "पंढरपुरी आहे माझा मायबाप ॥ १ ॥",
      "पिवळा पितांबर कैसा गगनी झळकला ।",
      "गरुडावरि बैसोनि माझा कैवारी आला ॥ २ ॥",
      "विठोबाचे राज्य आम्हा नित्य दीपवाळी ।",
      "विष्णुदास नामा जीवे भावे ओवाळी ॥ ३ ॥",
      "असो नसो भाव आम्हां तुझिया ठाया ।",
      "कृपादृष्टी पाहे माझ्या पंढरीराया ॥ ४ ॥",
    ],
    englishLyrics: [
      "Yeyi ho Vitthale maze mauli ye.",
      "Nidhalavari kar thevuni vaat mi pahe. (Dhru)",
      "Aaliya geliya haati dhaadi nirop.",
      "Pandharpuri aahe maza maybaap. (1)",
      "Pivala pitambar kaisa gagani zhalakala.",
      "Garudavari baisoni majha kaivari aala. (2)",
      "Vithobache rajya amha nitya deepavali.",
      "Vishnudas Nama jive bhave ovaali. (3)",
      "Aso naso bhaav amha tujhiya thaaya.",
      "Krupadrushti pahe majhya Pandhariraya. (4)",
    ],
    english: [
      "Come, O Vitthal, my mother, come.",
      "I stand with my hand shading my brow, watching the path for you.",
      "I send word through anyone who comes and goes.",
      "My mother and father dwell in Pandharpur.",
      "How the yellow silk garment shines against the sky.",
      "Seated upon Garuda, my protector has come.",
      "In Vithoba's kingdom, every day feels like Diwali for us.",
      "Vishnudas Nama offers this Aarti with heart and devotion.",
      "Whether or not we truly have devotion within us.",
      "Look upon me, O Lord of Pandhari, with your gracious gaze.",
    ],
  },
  {
    titleMarathi: "आरती ज्ञानराजा",
    titleEnglish: "Aarti Dnyanraja – Sant Dnyaneshwar Aarti",
    marathi: [
      "आरती ज्ञानराजा ॥ महाकैवल्यतेजा ॥",
      "सेविती साधुसंत ॥ मनु वेधला माझा ॥ धृ ॥",
      "लोपलें ज्ञान जगीं ॥ हित नेणती कोणी ॥",
      "अवतार पांडुरंग ॥ नाम ठेविलें ज्ञानी ॥ १ ॥",
      "कनकांचे ताट करीं ॥ उभ्या गोपिका नारी ॥",
      "नारद तुंबरु हो ॥ साम गायन करी ॥ २ ॥",
      "प्रगट गुह्य बोले ॥ विश्व ब्रह्मची केलें ॥",
      "रामा जनार्दनीं ॥ पायीं ठकचि ठेलें ॥ ३ ॥",
    ],
    englishLyrics: [
      "Aarti Dnyanraja. Mahakaivalyateja.",
      "Seviti sadhusant. Manu vedhala maza. (Dhru)",
      "Lopale dnyan jagi. Hit nenati koni.",
      "Avatar Pandurang. Naam thevile dnyani. (1)",
      "Kanakanche taat kari. Ubhya gopika naari.",
      "Narad Tumbaru ho. Saam gaayan kari. (2)",
      "Pragat guhya bole. Vishwa brahmachi kele.",
      "Rama Janardani. Payi thakachi thele. (3)",
    ],
    english: [
      "Aarti to Dnyanraja, the great radiance of ultimate liberation.",
      "Saints and sages worship him; my mind is wholly drawn to him.",
      "True knowledge had vanished from the world; no one grasped its essence.",
      "He is the incarnation of Pandurang; the wise gave him the name 'Dnyani.'",
      "Golden plates are held aloft, with the gopika women standing around.",
      "Narad and Tumbaru sing the sacred Sama hymns.",
      "He reveals the hidden truth, declaring the whole universe to be Brahman itself.",
      "Absorbed in the divine (Rama Janardan), he surrendered completely at the Lord's feet.",
    ],
  },
  {
    titleMarathi: "आरती तुकारामा",
    titleEnglish: "Aarti Tukarama – Sant Tukaram Aarti",
    marathi: [
      "आरती तुकारामा ॥ स्वामी सदगुरू धामा ॥",
      "सच्चिदानंद मूर्ति ॥ पाय दाखवी आम्हां ॥ धृ ॥",
      "राघवे सागरांत ॥ पाषाण तारीले ॥",
      "तैसे हे तुकोबाचे ॥ अभंग उदकी रक्षिले ॥ १ ॥",
      "तुकितां तुलनेसी ॥ ब्रम्ह तुकाशी आलें ॥",
      "म्हणोनि रामेश्वरे ॥ चरणीं मस्तक ठेविलें ॥ २ ॥",
    ],
    englishLyrics: [
      "Aarti Tukarama. Swami sadguru dhama.",
      "Sacchidananda murti. Paya dakhavi amha. (Dhru)",
      "Raghave sagaranta. Pashana tarile.",
      "Taise he Tukobache. Abhang udaki rakshile. (1)",
      "Tukita tulanesi. Brahma tukasi aale.",
      "Mhanoni Rameshware. Charani mastak thevile. (2)",
    ],
    english: [
      "Aarti to Tukaram, the very abode of the true Guru.",
      "O form of Existence-Consciousness-Bliss, show us your grace-giving feet.",
      "Just as Raghava made stones float upon the ocean,",
      "so too Tukoba's Abhangas were preserved unharmed upon the river's waters.",
      "When weighed upon the scale, Brahman itself matched Tuka in weight,",
      "and so Lord Rameshwar bowed his own head at Tuka's feet.",
    ],
  },
  {
    titleMarathi: "गजानना गजानना",
    titleEnglish: "Gajanana Gajanana",
    marathi: [
      "गजानना गजानना ॥ पार्वतीनंदना मोरया गजानना ॥ (२)",
      "गजानना तुझी आवड मोठी ॥ धावत आलो आरतीसाठी ॥ (२)",
      "हरिभजनाची आवड मोठी ॥ धावत आलो आरतीसाठी ॥ (२)",
      "हिरवा चाफा पिवळी फुले ॥ त्याचा मोकळा गजरा ॥ (२)",
      "पार्वतीचा पुत्र गजानन ॥ त्याची सेवा करा ॥ (२)",
      "गजानना गजानना ॥ पार्वतीनंदना मोरया गजानना ॥",
      "ताड वाजे वीणा वाजे ॥ वाजे मृदुंग ॥ (२)",
      "त्या तालावर नाचे मोरया ॥ श्री गजानना ॥ (२)",
      "गजानना गजानना ॥ पार्वतीनंदना मोरया गजानना ॥",
      "भक्तमंडळींनी पत्र पाठविले ॥ अष्टविनायकाला ॥ (२)",
      "पत्र वाचूनी आनंद झाला ॥ श्री गजानना ॥ (२)",
      "गजानना गजानना ॥ पार्वतीनंदना मोरया गजानना ॥",
    ],
    englishLyrics: [
      "Gajanana Gajanana. Parvatinandana Morya Gajanana. (2)",
      "Gajanana tuzi aavad mothi. Dhavat aalo aartisathi. (2)",
      "Hari bhajanachi aavad mothi. Dhavat aalo aartisathi. (2)",
      "Hirva chafa pivli fule. Tyacha mokla gajra. (2)",
      "Parvaticha putra Gajanan. Tyachi seva kara. (2)",
      "Gajanana Gajanana. Parvatinandana Morya Gajanana.",
      "Taad vaje vina vaje. Vaje mridung. (2)",
      "Tya talavar nache Morya. Shri Gajanana. (2)",
      "Gajanana Gajanana. Parvatinandana Morya Gajanana.",
      "Bhaktamandalinni patra pathavile. Ashtavinayakala. (2)",
      "Patra vachuni anand zala. Shri Gajanana. (2)",
      "Gajanana Gajanana. Parvatinandana Morya Gajanana.",
    ],
    english: [
      "Gajanana, Gajanana — son of Parvati, Morya Gajanana.",
      "O Gajanana, my love for you is boundless; I have come running for your Aarti.",
      "My love for singing Hari's devotional songs is boundless; I have come running for your Aarti.",
      "Green Champa blossoms and yellow flowers, strung into a loose fragrant garland.",
      "Gajanan, the son of Parvati — devote yourselves to his service.",
      "Gajanana, Gajanana — son of Parvati, Morya Gajanana.",
      "The cymbals ring, the veena plays, the mridang drum resounds.",
      "To that very rhythm, Morya — Shri Gajanana — dances.",
      "Gajanana, Gajanana — son of Parvati, Morya Gajanana.",
      "The devotees sent a letter to the Ashtavinayak, the eight sacred shrines of Ganesha.",
      "Upon reading the letter, Shri Gajanana was filled with joy.",
      "Gajanana, Gajanana — son of Parvati, Morya Gajanana.",
    ],
  },
  {
    titleEnglish:
      "Nache Ganesh Ne Nache Hanuman – Agad Bam (Narsinh Mehta Bhajan)",
    original: [
      "Nache Ganesha Ne Nache Hanuman (2), Parvatina PraanNath Bhola Bhagwaan.",
      "Agad Bam, Agad Bam, Daak Vaagey Damru, Nache Sadashiv Aagey Bhairu (2)",
      "Bhaang Vavi, Bholanath Aye Ninde Che Ganesh (2), ParvatiJi Pani Vaaley Chuta Meli Kesh.",
      "Aey Bhaang Kera Rotla Ne Dhatura Nu Shaak (2), Pirse Maiya Parvati Ne Jamey Bholanath.",
      "Haath Lishi Bhabhuti Ne Chole Che Ang (2), Dekho Maiya Parvati Ji, Keso Bhayo Rang.",
      "Naag Kera Bajubandh, Naag Kero Haar (2), Naagin Na Shringaar, Sohave Bholanath.",
      "Koi Pujave Ang, Baba Koi Pujave Pag (2), Narshi Mehta Puje, Apuj Ling.",
      "Maadi Ramey Garba, Ne Radha Ramey Raas (2), Bholanath Khijey Karey Tandav Naach.",
    ],
    marathi: [
      "गणेश नाचते हैं, हनुमान भी नाचते हैं, पार्वती के प्राणनाथ भोले भगवान भी नाचते हैं।",
      "अगड़ बम, अगड़ बम, डमरू बजता है; सदाशिव के आगे भैरव नाचते हैं।",
      "भांग पीकर भोलानाथ झूमते हैं, गणेश उन्हें छेड़ते हुए टोकते हैं; पार्वती जी बाल खुले छोड़कर पानी भरने जाती हैं।",
      "भांग की रोटी और धतूरे की सब्ज़ी — माता पार्वती परोसती हैं और भोलानाथ खाते हैं।",
      "हाथ में भभूति लेकर वे शरीर पर मलते हैं; देखो माता पार्वती जी, कैसा रंग चढ़ गया है!",
      "नाग का बाजूबंद, नाग का हार, नागिन का श्रृंगार — यही भोलानाथ को शोभा देता है।",
      "कोई उनके अंग की पूजा करता है, कोई चरणों की; नरसी मेहता तो उस निराकार, अपूज्य लिंग की ही पूजा करते हैं।",
      "माता गरबा खेलती हैं, राधा रास रचाती हैं; भोलानाथ रुष्ट होकर तांडव नृत्य करते हैं।",
    ],
    english: [
      "Ganesha dances, Hanuman dances too — and so does Bhola Bhagwan, the beloved lord of Parvati.",
      "Agad Bam, Agad Bam — the damru drum resounds; Bhairav dances before Sadashiv.",
      "Having drunk bhang, Bholanath sways; Ganesha teasingly scolds him, while Parvati goes to fetch water with her hair let loose.",
      "Bread made with bhang and a curry of dhatura (thorn-apple) — Mother Parvati serves it, and Bholanath eats.",
      "Taking sacred ash in hand, he smears it over his body; behold, Mother Parvati, what a hue it has taken on!",
      "Serpents form his armlets, serpents form his necklace — adorned with serpent ornaments, Bholanath looks resplendent.",
      "Some worship his form, some worship his feet — but Narsi Mehta worships the formless, unadorned Linga itself.",
      "Mother plays Garba, and Radha performs the Raas; when roused, Bholanath performs the Tandava dance.",
    ],
  },
  {
    titleMarathi: "घालीन लोटांगण",
    titleEnglish: "Ghalin Lotangan – Mantrapushpanjali",
    marathi: [
      "घालीन लोटांगण, वंदीन चरण ।",
      "डोळ्यांनी पाहीन रुप तुझें ।",
      "प्रेमें आलिंगिन, आनंदे पूजिन ।",
      "भावें ओवाळीन म्हणे नामा ॥ १ ॥",
      "त्वमेव माता च पिता त्वमेव ।",
      "त्वमेव बंधुश्च सखा त्वमेव ।",
      "त्वमेव विद्या द्रविणं त्वमेव ।",
      "त्वमेव सर्वं मम देवदेव ॥ २ ॥",
      "कायेन वाचा मनसेंद्रियैर्वा ।",
      "बुद्ध्यात्मना वा प्रकृतिस्वभावात् ।",
      "करोमि यद्यत् सकलं परस्मै ।",
      "नारायणायेति समर्पयामि ॥ ३ ॥",
      "अच्युतं केशवं रामनारायणं ।",
      "कृष्णदामोदरं वासुदेवं भजे ।",
      "श्रीधरं माधवं गोपिकावल्लभं ।",
      "जानकीनायकं रामचंद्रं भजे ॥ ४ ॥",
      "हरे राम हरे राम, राम राम हरे हरे ।",
      "हरे कृष्ण हरे कृष्ण, कृष्ण कृष्ण हरे हरे ॥",
    ],
    englishLyrics: [
      "Ghalin lotangan, vandin charan.",
      "Dolyani pahin rup tujhe.",
      "Preme alingin, anande pujin.",
      "Bhave ovalin mhane Nama. (1)",
      "Twamev mata cha pita twamev.",
      "Twamev bandhushcha sakha twamev.",
      "Twamev vidya dravinam twamev.",
      "Twamev sarvam mam devadeva. (2)",
      "Kayena vacha manasendriyairva.",
      "Buddhyatmana va prakritisvabhavat.",
      "Karomi yadyat sakalam parasmai.",
      "Narayanayeti samarpayami. (3)",
      "Achyutam Keshavam Ramnarayanam.",
      "Krishnadamodaram Vasudevam bhaje.",
      "Shridharam Madhavam Gopikavallabham.",
      "Janakinayakam Ramchandram bhaje. (4)",
      "Hare Ram Hare Ram, Ram Ram Hare Hare.",
      "Hare Krishna Hare Krishna, Krishna Krishna Hare Hare.",
    ],
    english: [
      "I prostrate fully on the ground and bow at your feet.",
      "With my eyes, I behold your divine form.",
      "With love I embrace you, with joy I worship you.",
      "With devotion I offer this Aarti — so says Namdev.",
      "You alone are my mother, and you alone my father.",
      "You alone are my brother, and you alone my friend.",
      "You alone are my knowledge, and you alone my wealth.",
      "You alone are everything to me, O God of gods.",
      "Whatever I do with body, speech, mind, or senses,",
      "with my intellect, my self, or by my inborn nature —",
      "whatever actions I perform, all of it, to the Supreme,",
      "to Narayana, I offer completely.",
      "I worship Achyuta, Keshava, and Ram-Narayana,",
      "Krishna-Damodara, and Vasudeva.",
      "I worship Shridhara, Madhava, the beloved of the Gopis,",
      "the Lord of Janaki, Ramchandra.",
      "Hare Ram Hare Ram, Ram Ram Hare Hare.",
      "Hare Krishna Hare Krishna, Krishna Krishna Hare Hare.",
    ],
  },
];

export default aartis;
