const aartis = [
  {
    titleMarathi: "सुखकर्ता दुःखहर्ता",
    titleEnglish: "Sukhkarta Dukhharta – Ganpati Aarti",
    marathi: [
      "सुखकर्ता दुःखहर्ता वार्ता विघ्नाची ।",
      "नुरवी पुरवी प्रेम कृपा जयाची ॥ धृ ॥",
      "सर्वांगी सुंदर उटी शेंदुराची ।",
      "कंठी झळके माळ मुक्ताफळांची ॥ जया ॥ १ ॥",
      "जय देव जय देव जय मंगलमूर्ती ।",
      "दर्शनमात्रे मनःकामना पूर्ती ।",
      "रत्नखचित फरा तुज गौरीकुमरा ।",
      "चंदनाची उटी कुंकुमकेशरा ।",
      "हिरेजडित मुकुट शोभतो बरा ।",
      "रुणझुणती नूपुरे चरणी घागरिया ॥ जया ॥ २ ॥",
      "लंबोदर पीतांबर फणिवरबंधना ।",
      "सरळ सोंड वक्रतुंड त्रिनयना ।",
      "दास रामाचा वाट पाहे सदना ।",
      "संकटी पावावे निर्वाणी रक्षावे सुरवर वंदना ।",
      "जय देव जय देव जय मंगलमूर्ती ।",
      "दर्शनमात्रे मनःकामना पूर्ती ॥ जया ॥ ३ ॥",
    ],
    englishLyrics: [
      "Sukhkarta dukhharta varta vighnachi.",
      "Nurvi purvi prem krupa jayachi. (Refrain)",
      "Sarvangi sundar uti shendurachi.",
      "Kanthi zhalake maal muktaphalaanchi. (Jaya 1)",
      "Jai dev jai dev jai mangalmurti.",
      "Darshanmatre manah kaamana purti.",
      "Ratnakhachit phara tuj gaurikumara!",
      "Chandnachi uti kunkumakeshara.",
      "Hirejadit mukut shobhato bara.",
      "Runjhunti nupure charni ghagariya. (Jaya 2)",
      "Lambodar pitambar phanivar bandhana.",
      "Saral sond vakra tund trinayana.",
      "Daas Ramacha vat pahe sadana.",
      "Sankati paavaave nirvaani rakshaave survar vandana.",
      "Jai dev jai dev jai mangalmurti.",
      "Darshanmatre manah kaamana purti. (Jaya 3)",
    ],
    english: [
      "Sukhkarta Dukhharta – the one who removes sorrow and grants happiness, remove all obstacles.",
      "Fill our lives with love, grace and blessings.",
      "Your entire form is beautiful and adorned with vermilion.",
      "A pearl necklace shines around your neck.",
      "Victory to you, O auspicious and divine form.",
      "Just seeing you fulfills the wishes of the heart.",
      "O son of Goddess Gauri, adorned with precious jewels.",
      "Your forehead is decorated with sandalwood and saffron.",
      "Your diamond-studded crown shines beautifully.",
      "Your anklets ring melodiously as you walk.",
      "O large-bellied Lord wearing yellow garments.",
      "With your straight trunk, curved form and three eyes.",
      "Your devotee waits for you with devotion.",
      "Protect us during difficult times and bless us.",
      "Victory to you, O auspicious and divine form.",
      "Your divine presence fulfills the wishes of the heart.",
    ],
  },
  {
    titleMarathi: "श्री शंकराची आरती",
    titleEnglish: "Shri Shankarachi Aarti",
    marathi: [
      "लवथवती विक्राळा ब्रह्मांडी माळा ।",
      "विषें कंठ काळा त्रिनेत्री ज्वाळा ॥",
      "लावण्यसुंदर मस्तकी बाळा ।",
      "तेथुनियां जळ निर्मळ वाहे झुळझुळा ।",
      "जय देव जय देव श्रीशंकरा ।",
      "आरती ओवाळूं तुज कर्पूरगौरा ॥ १ ॥",
      "कर्पूरगौरा भोळा नयनी विशाळा ।",
      "अर्धांगी पार्वती सुमनांच्या माळा ।",
      "विभूतीचे उधळण शितिकंठ नीळा ।",
      "ऐसा शंकर शोभे उमावेल्हाळा जय ॥ २ ॥",
      "देवी दैत्य सागरमंथन पै केले ।",
      "त्यामाजी अवचित हलाहल उठिले ।",
      "तें त्वां असुरपणे प्राशन केले ।",
      "नीलकंठ नाम प्रसिद्ध झाले ॥ जया ॥ ३ ॥",
      "व्याघ्रांबर फणिवरधर सुंदर मदनारी ।",
      "पंचवदन मनमोहन मुनिजनसुखकारी ।",
      "शतकोटींचे बीज वाचे उच्चारी ।",
      "रघुकुळटिळक रामदासा अंतरी ॥ जय ॥ ४ ॥",
    ],
    englishLyrics: [
      "Lavathavati vikraala brahmandi maala.",
      "Vishe kanth kaala trinetri jwala.",
      "Lavanya sundar mastki baala.",
      "Tethuniya jal nirmal vahe zhulzhula.",
      "Jai dev jai dev Shri Shankara.",
      "Aarti ovalu tuj karpurgaura. (1)",
      "Karpurgaura bhola nayani vishaala.",
      "Ardhangi Parvati sumnanchya maala.",
      "Vibhutiche udhalan shitikanth neela.",
      "Aisa Shankar shobhe Umavelhala. (2)",
      "Devi daitya sagar-manthan pai kele.",
      "Tyamaji avchit halahal uthile.",
      "Te twa asur-pane prashan kele.",
      "Neelkanth naam prasiddh zale. (3)",
      "Vyaghrambar phanivardhar sundar madanari.",
      "Panchvadan manmohan munijan sukhkari.",
      "Shatkotinche beej vache uchhari.",
      "Raghukulatilak Ramdasa antari. (4)",
    ],
    english: [
      "O Lord Shiva, mighty and magnificent throughout the universe.",
      "Your throat is darkened by poison and your three eyes shine like flames.",
      "Your form is beautiful and divine.",
      "Pure water flows gently from your sacred locks.",
      "Victory to Lord Shankara.",
      "We offer this camphor Aarti to you, O radiant Lord.",
      "You are pure, simple and compassionate, with large beautiful eyes.",
      "Goddess Parvati is your divine consort.",
      "Your blue throat and sacred ash make you majestic.",
      "Such is the beautiful form of Lord Shankara.",
      "During the churning of the ocean, deadly poison emerged.",
      "You drank the poison to protect the world.",
      "Because of this your throat became blue.",
      "You became famous as Neelkanth.",
      "You wear tiger skin and carry the serpent.",
      "Your five-faced form is beautiful and brings happiness to sages.",
      "Your divine name is praised with devotion.",
    ],
  },
  {
    titleMarathi: "दुर्गादेवीची आरती",
    titleEnglish: "Durgadevichi Aarti",
    marathi: [
      "दुर्गे दुर्घट भारी तुजविण संसारी ।",
      "अनाथनाथे अंबे करुणा विस्तारी ॥",
      "वारी वारी जन्ममरणाते वारी ।",
      "हारी पडलों आता संकट निवारी ॥",
      "जय देवी जय देवी महिषासुरमथिनी ।",
      "सुरवरईश्वरवरदे तारक संजीवनी ॥ जय ॥ १ ॥",
      "त्रिभुवनभुवनी पाहतां तुज ऐसी नाही ।",
      "चारी श्रमले परंतु न बोलवे काही ॥",
      "साही विवाद करितां पडले प्रवाही ।",
      "ते तूं भक्तालागीं पावसि लवलाही ॥ जय ॥ २ ॥",
      "प्रसन्नवदने प्रसन्न होसी निजदासा ।",
      "क्लेशापासुनी सोडी तोडी भवपाशा ।",
      "अंबे तुजवाचून कोण पुरवील आशा ।",
      "नरहरी तल्लीन झाला पदपंकजलेशा ॥ जय ॥ ३ ॥",
    ],
    englishLyrics: [
      "Durge durghat bhari tujavin sansari.",
      "Anathnathe Ambe karuna vistari.",
      "Vari vari janm-maranate vari.",
      "Hari padlo aata sankat nivari.",
      "Jai devi jai devi Mahishasur mathini.",
      "Suravar-Ishvar-varade tarak sanjivani. (1)",
      "Tribhuvanbhuvani pahata tuj aisi nahi.",
      "Chaari shramale parantu na bolave kahi.",
      "Saahi vivaad karita padle pravahi.",
      "Te tu bhaktalagi pavsi lavlahi. (2)",
      "Prasannvadane prasann hosi nijdasa.",
      "Kleshapasuni sodi todi bhavpasha.",
      "Ambe tujavachun kon purvil aasha.",
      "Narahari tallin zhala padpankaj-lesha. (3)",
    ],
    english: [
      "O Goddess Durga, the world is difficult without you.",
      "O Mother of the helpless, spread your compassion upon us.",
      "Protect us from the endless cycle of birth and death.",
      "We have fallen into difficulties; please remove our troubles.",
      "Victory to Goddess Durga, destroyer of Mahishasura.",
      "You grant blessings and protect the divine and devoted.",
      "There is none like you in all the three worlds.",
      "Even after trying to describe you, words fall short.",
      "Those who debate your greatness are left without words.",
      "You quickly come to the aid of your devotees.",
      "With your pleasant face, you bless your devoted servants.",
      "Free us from suffering and from the bonds of worldly life.",
      "O Mother, who else can fulfill our deepest hopes?",
      "Your devotee becomes completely absorbed at your lotus feet.",
    ],
  },
  {
    titleMarathi: "विठोबाची आरती",
    titleEnglish: "Vitthobachi Aarti",
    marathi: [
      "युगे अठ्ठावीस विटेवरी उभा ।",
      "वामांगी रखुमाई दिसे दिव्य शोभा ।",
      "पुंडलिकाचे भेटी परब्रह्म आले गा ।",
      "चरणी वाहे भीमा उद्धरी जगा ।",
      "जय देव जय देव जय पांडुरंगा ।",
      "रखुमाईवल्लभा राईच्या वल्लभा पावे जिवलगा ॥ १ ॥",
      "तुळशीमाळा गळां कर ठेवुनी कटी ।",
      "कांसे पीतांबर कस्तुरी लल्लाटीं ।",
      "देव सुरवर नित्य येती भेटी ।",
      "गरुड हनुमंत पुढे उभे राहती ॥ २ ॥",
      "धन्य वेणुनाद अनुपाळा गळा ।",
      "सुवर्णाची कमळे चरणाला गळा ।",
      "राई रखुमाई राणीया सकळा ।",
      "ओवाळिती राजा विठोबा सावळा ॥ ३ ॥",
      "ओवाळू आरत्या कुर्वंड्या येती ।",
      "चंद्रभागेमाजी सोडुनिया देती ।",
      "दिंड्या पताका वैष्णव नाचती ।",
      "पंढरीचा महिमा वर्णावा किती ॥ ४ ॥",
      "आषाढी कार्तिकी भक्तजन येती ।",
      "चंद्रभागेमाजी स्नान जे करती ।",
      "दर्शन होताचि तया होय मुक्ति ।",
      "केशवासी नामदेव भावे ओवाळिती ॥ ५ ॥",
    ],
    englishLyrics: [
      "Yuge atthavis vitevari ubha.",
      "Vamangi Rakhumai dise divya shobha.",
      "Pundalikache bheti parbrahma aale ga.",
      "Charani vahe Bhima uddhari jaga.",
      "Jai dev jai dev jai Panduranga.",
      "Rakhumaivallabha Raicheya vallabha pave jivalga. (1)",
      "Tulsimala gala kar thevuni kati.",
      "Kanse pitambar kasturi lallati.",
      "Dev suravar nitya yeti bheti.",
      "Garud Hanumant pudhe ubhe rahati. (2)",
      "Dhanya venunad anupala gala.",
      "Suvarnachi kamale charnala gala.",
      "Rai Rakhumai raniya sakala.",
      "Ovaliti raja Vitthoba savala. (3)",
      "Ovalu aartya kurvandya yeti.",
      "Chandrabhagemaji soduniya deti.",
      "Dindya pataka Vaishnav nachati.",
      "Pandharicha mahima varnava kiti. (4)",
      "Ashadhi Kartiki bhakta-jan yeti.",
      "Chandrabhagemaji snan je karati.",
      "Darshan hotach taya hoy mukti.",
      "Keshvasi Namdev bhave ovaliti. (5)",
    ],
    english: [
      "For twenty-eight ages, you stand upon the sacred brick.",
      "Rukmini stands beside you in divine beauty.",
      "The Supreme Being came to meet devotee Pundalik.",
      "The Bhima River flows at your feet and blesses the world.",
      "Victory to Panduranga, the beloved Lord.",
      "Beloved of Rukmini and the devotee's cherished Lord.",
      "You wear a Tulsi garland and rest your hands upon your waist.",
      "You wear yellow garments with sandalwood and musk adorning you.",
      "Gods and divine beings come to see you every day.",
      "Garuda and Hanuman stand before you.",
      "The beautiful sound of the flute fills the surroundings.",
      "Golden lotuses adorn your sacred feet.",
      "Rukmini and the divine queens worship you.",
      "They perform Aarti to the beautiful dark form of Vitthoba.",
      "Devotees gather with Aarti and offerings.",
      "Devotees bathe in the Chandrabhaga River.",
      "Processions and Vaishnav devotees dance with flags.",
      "The greatness of Pandharpur cannot be fully described.",
      "Devotees arrive during Ashadhi and Kartiki.",
      "Those who bathe in the Chandrabhaga receive blessings.",
      "A vision of the Lord brings liberation.",
      "Devotees lovingly offer Aarti to Lord Keshava.",
    ],
  },
]

export default aartis
